User can create a flashcard
StevenNagata/react-flash-cards pull request #2
Opened 2018-10-02 21:34 UTC by StevenNagata

![react-flashcards-issue1](https://user-images.githubusercontent.com/42354826/46378349-2a0d5400-c650-11e8-86f7-11cf2083e90c.gif)

2018-10-02 22:56 UTC, thebearingedge requested changes

2018-10-02 22:56 UTC, thebearingedge commented on src/flashcard-form.js
> +      <div className="container-fluid w-50 border border-dark p-4 rounded">
Dark borders are _super_ risky. I don't really recommend using them unless you are diligent about applying them everywhere. And even then, it's probably not going to look that great.

2018-10-02 22:56 UTC, thebearingedge commented on src/flashcard-form.js
> +            <label htmlFor="formGroupExampleInput">Question</label>
Match your `htmlFor` to the actual `id` of the input you're labeling.

2018-10-02 22:56 UTC, thebearingedge commented on src/index.html
> +  <link href="https://fonts.googleapis.com/css?family=Caveat|Kalam" rel="stylesheet"/>
If you really want a more custom feel to your UI, you can choose a theme from here: https://bootswatch.com/
And link it from here: https://cdnjs.com/libraries/bootswatch

Avoid custom styles for this project. We want to concentrate on functionality and, unfortunately, you'll be judged on how it looks even though you haven't studied design.

2018-10-02 22:56 UTC, thebearingedge commented on src/app.js
> +  saveFlashcard(event) {
Try to move most of this method into your form component. `saveFlashCard` shouldn't be concerned with `event`s and element values. Instead, define a method that simply receives a new `flashCard` object and adds it to state. Push the work of building this object down into the form component.

2018-10-02 23:30 UTC, StevenNagata commented
![react-flashcards-issue1](https://user-images.githubusercontent.com/42354826/46382571-7791bd00-c660-11e8-938d-6a7202ef3298.gif)

2018-10-03 17:17 UTC, thebearingedge requested changes

2018-10-03 17:17 UTC, thebearingedge commented on src/app.js
> +    const flashcards = this.state.flashcards.map((card) =>
You don't need to copy every object in the array, just the array itself so you can add an object.

2018-10-03 17:17 UTC, thebearingedge commented on src/app.js
> +    event.target.reset()
Let the form component do the resetting.

2018-10-03 17:17 UTC, thebearingedge commented on src/styles.css
> +
You can add this file when it's needed.

2018-10-03 17:40 UTC, thebearingedge approved these changes

2018-10-03 17:45 UTC, merged